Repository Quick/Quick, pull requests merged in 2022-06, with the labels that each got.

#1152 Renamed Configuration -> QCKConfiguration on documentation
  Documentation/en-us/ConfiguringQuick.md
  Documentation/ja/ConfiguringQuick.md
  Documentation/ko-kr/ConfiguringQuick.md
  Documentation/zh-cn/ConfiguringQuick.md
Labels: documentation

#1156 Fix sporadic crashes caused by finding classes that don't play well with isSubclass(of:)
  Quick.xcodeproj/project.pbxproj
  Sources/Quick/Configuration/QuickConfiguration.swift
  Sources/Quick/QuickTestObservation.swift
  Sources/Quick/SubclassDetection.swift
  Tests/QuickTests/QuickTests/FunctionalTests/SubclassDetectionSpec.swift
  Tests/QuickTests/QuickTests/Helpers/QuickSpecRunner.swift
Labels: bug

#1146 Raise minimum supported versions to macOS 10.15, iOS 13, tvOS 13
  .github/workflows/ci-swiftpm.yml
  .github/workflows/ci-xcode.yml
  .github/workflows/cocoapods.yml
  Documentation/en-us/InstallingQuick.md
  Package.swift
  Quick.podspec
  Quick.xcodeproj/project.pbxproj
  Sources/Quick/Example.swift
  Tests/LinuxMain.swift
  Tests/QuickTests/QuickTests/FunctionalTests/ObjC/SelectedTests+ObjC.m
Labels: enhancement, breaking change

#1158 Fix tests broken by Nimble 10 update
  .github/workflows/ci-swiftpm.yml
  .github/workflows/ci-xcode.yml
  Tests/QuickTests/QuickTests/FunctionalTests/QuickSpec_SelectedTests.swift
Labels: bug
