Repository Quick/Quick, pull requests merged in 2022-04, with the labels that each got.

#1133 [Breaking] Rename Configuration -> QCKConfiguration
  Quick.xcodeproj/project.pbxproj
  Sources/Quick/Configuration/QCKConfiguration.swift
  Sources/Quick/Configuration/QuickConfiguration.swift
  Sources/Quick/World.swift
  Sources/QuickObjectiveC/Configuration/QuickConfiguration.h
  Sources/QuickObjectiveC/Configuration/QuickConfiguration.m
  Tests/QuickTests/QuickFocusedTests/FocusedTests+ObjC.m
  Tests/QuickTests/QuickFocusedTests/FocusedTests.swift
  Tests/QuickTests/QuickTests/Fixtures/FunctionalTests_SharedExamplesTests_SharedExamples.swift
  Tests/QuickTests/QuickTests/FunctionalTests/Configuration/AfterEach/Configuration+AfterEach.swift
  Tests/QuickTests/QuickTests/FunctionalTests/Configuration/BeforeEach/Configuration+BeforeEach.swift
  Tests/QuickTests/QuickTests/FunctionalTests/ObjC/SharedExamples+BeforeEachTests+ObjC.m
  Tests/QuickTests/QuickTests/FunctionalTests/SharedExamples+BeforeEachTests.swift
Labels: breaking change

#1132 Add aroundEach
  Quick.xcodeproj/project.pbxproj
  Sources/Quick/Configuration/QCKConfiguration.swift
  Sources/Quick/DSL/DSL.swift
  Sources/Quick/DSL/World+DSL.swift
  Sources/Quick/Example.swift
  Sources/Quick/ExampleGroup.swift
  Sources/Quick/Hooks/Closures.swift
  Sources/Quick/Hooks/ExampleHooks.swift
  Sources/QuickObjectiveC/DSL/QCKDSL.h
  Sources/QuickObjectiveC/DSL/QCKDSL.m
  Tests/QuickTests/QuickTests/FunctionalTests/AroundEachTests.swift
  Tests/QuickTests/QuickTests/FunctionalTests/ObjC/AroundEachTests+ObjC.m
Labels: feature

#1116 Add support for running a single test
  Quick.xcodeproj/project.pbxproj
  Sources/Quick/QuickSelectedTestSuiteBuilder.swift
  Sources/Quick/QuickTestSuite.swift
  Sources/QuickObjectiveC/XCTestSuite+QuickTestSuiteBuilder.m
  Tests/QuickTests/QuickTestHelpers/XCTestCaseProvider.swift
  Tests/QuickTests/QuickTests/FunctionalTests/ObjC/SelectedTests+ObjC.m
  Tests/QuickTests/QuickTests/FunctionalTests/QuickSpec_SelectedTests.swift
Labels: feature

#1136 [v5.0.0] release prep
  Quick.podspec
  docs/Classes.html
  docs/Classes/Behavior.html
  docs/Classes/Callsite.html
  docs/Classes/Example.html
  docs/Classes/ExampleGroup.html
  docs/Classes/ExampleMetadata.html
  docs/Classes/QCKConfiguration.html
  docs/Classes/QuickConfiguration.html
  docs/Classes/QuickTestSuite.html
  docs/Functions.html
  docs/Typealiases.html
  docs/badge.svg
  docs/docsets/Quick.docset/Contents/Resources/Documents/Classes.html
  docs/docsets/Quick.docset/Contents/Resources/Documents/Classes/Behavior.html
  docs/docsets/Quick.docset/Contents/Resources/Documents/Classes/Callsite.html
  docs/docsets/Quick.docset/Contents/Resources/Documents/Classes/Example.html
  docs/docsets/Quick.docset/Contents/Resources/Documents/Classes/ExampleGroup.html
  docs/docsets/Quick.docset/Contents/Resources/Documents/Classes/ExampleMetadata.html
  docs/docsets/Quick.docset/Contents/Resources/Documents/Classes/QCKConfiguration.html
  docs/docsets/Quick.docset/Contents/Resources/Documents/Classes/QuickConfiguration.html
  docs/docsets/Quick.docset/Contents/Resources/Documents/Classes/QuickTestSuite.html
  docs/docsets/Quick.docset/Contents/Resources/Documents/Functions.html
  docs/docsets/Quick.docset/Contents/Resources/Documents/Typealiases.html
  docs/docsets/Quick.docset/Contents/Resources/Documents/index.html
  docs/docsets/Quick.docset/Contents/Resources/Documents/search.json
  docs/docsets/Quick.docset/Contents/Resources/docSet.dsidx
  docs/index.html
  docs/search.json
  docs/undocumented.json
Labels: enhancement, documentation

#1143 Fix running tests in parallel
  Quick.xcodeproj/xcshareddata/xcschemes/Quick-iOS.xcscheme
  Quick.xcodeproj/xcshareddata/xcschemes/Quick-macOS.xcscheme
  Quick.xcodeproj/xcshareddata/xcschemes/Quick-tvOS.xcscheme
  Sources/QuickObjectiveC/XCTestSuite+QuickTestSuiteBuilder.m
  Tests/QuickTests/QuickTests/FunctionalTests/ObjC/SelectedTests+ObjC.m
Labels: bug

#1098 Report skipped tests to Xcode
  Sources/Quick/Example.swift
  Tests/QuickTests/QuickTests/FunctionalTests/ItTests.swift
Labels: enhancement, feature
